IF NOT EXISTS (SELECT 1 FROM dbo.WEB_TRANSLATIONS WHERE TRANSLATION_KEY = 'comingSoon') 
INSERT INTO dbo.WEB_TRANSLATIONS (TRANSLATION_KEY, EN_VALUE, AR_VALUE) 
VALUES ('comingSoon', 'Coming Soon', N'قريباً');
