const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001';

export const API_ENDPOINTS = {
  BASE_URL: API_BASE_URL,
  LOGIN: `${API_BASE_URL}/api/login`,
  HEALTH: `${API_BASE_URL}/api/health`,
  ITEM_SEARCH: `${API_BASE_URL}/api/items/search`,
  ITEM_CACHE: `${API_BASE_URL}/api/items/cache`,
  CUSTOMER_SEARCH: `${API_BASE_URL}/api/customers/search`,
  CUSTOMER_CACHE: `${API_BASE_URL}/api/customers/cache`,
  CUSTOMER_LIST: `${API_BASE_URL}/api/customers/list`,
  CUSTOMER_BY_ID: (id) => `${API_BASE_URL}/api/customers/${id}`,
  CUSTOMER_INFO: (accNo) => `${API_BASE_URL}/api/customers/${accNo}/info`,
  ACCOUNT_CACHE: `${API_BASE_URL}/api/accounts/cache`,
  ACCOUNT_LIST: `${API_BASE_URL}/api/accounts/list`,
  ACCOUNT_ALL: `${API_BASE_URL}/api/accounts/all`,
  ACCOUNT_CLASSES: `${API_BASE_URL}/api/accounts/classes`,
  ACCOUNT_SUBCLASSES: (classCode) => `${API_BASE_URL}/api/accounts/subclasses?classCode=${classCode}`,
  ACCOUNT_HEADER_ACCOUNTS: (subClassCode) => `${API_BASE_URL}/api/accounts/header-accounts?subClassCode=${subClassCode}`,
  ACCOUNT_BY_LEVEL: (classCode, level) => `${API_BASE_URL}/api/accounts/by-level?classCode=${classCode}&level=${level}`,
  ACCOUNT_LIST_BY_PARENT: (level, id) => `${API_BASE_URL}/api/accounts/list-by-parent?parentLevel=${level}&parentId=${id}`,
  CASH_POLICY: `${API_BASE_URL}/api/options/cash-policy`,
  CUSTOMER_POLICY: `${API_BASE_URL}/api/options/customer-policy`,
  SUPPLIER_POLICY: `${API_BASE_URL}/api/options/supplier-policy`,
  SUPPLIER_LIST: `${API_BASE_URL}/api/suppliers/list`,
  SUPPLIER_SEARCH: `${API_BASE_URL}/api/suppliers/search`,
  SUPPLIER_CACHE: `${API_BASE_URL}/api/suppliers/cache`,
  PURCHASE_POLICY: `${API_BASE_URL}/api/options/purchase-policy`,
  PURCHASE_LIST: `${API_BASE_URL}/api/purchases/list`,
  PURCHASE_SEARCH: `${API_BASE_URL}/api/purchases/search`,
  PURCHASE_CACHE: `${API_BASE_URL}/api/purchases/cache`,
  ACCOUNT_HEADER_TYPES: `${API_BASE_URL}/api/accounts/header-types`,
  ITEM_GROUPS: `${API_BASE_URL}/api/item-groups`,
  UNIT_MASTER: `${API_BASE_URL}/api/unit-master`,
  TRANSACTION_TYPES: `${API_BASE_URL}/api/transaction-types`,
  USER_PRIVILEGES: `${API_BASE_URL}/api/user-privileges`,
  USER_PRIVILEGES_GROUPS: `${API_BASE_URL}/api/user-privileges/groups`,
  USER_PRIVILEGES_MENU_HEADS: `${API_BASE_URL}/api/user-privileges/menu-heads`,
  USER_PRIVILEGES_GRID: `${API_BASE_URL}/api/user-privileges/grid`,
  USER_PRIVILEGES_BULK_SAVE: `${API_BASE_URL}/api/user-privileges/bulk-save`,
  USER_INFO: `${API_BASE_URL}/api/user-info`,
  ACCOUNT_CREATE: `${API_BASE_URL}/api/accounts/create`,
  INVOICE_NEXT: `${API_BASE_URL}/api/invoice/next`,
  SALES_SAVE: `${API_BASE_URL}/api/sales/save`,
  SALES_HISTORY: `${API_BASE_URL}/api/sales`,
  SALE_ITEMS: (recNo) => `${API_BASE_URL}/api/sales/${recNo}/items`,
  WAREHOUSE_LIST: `${API_BASE_URL}/api/warehouses/list`,
  BRANCHES: `${API_BASE_URL}/api/branches`,
  SCREENS: `${API_BASE_URL}/api/screens`,
  CURRENCY_LIST: `${API_BASE_URL}/api/currencies/list`,
  INVOICE_ADDRESS: (invoiceNo, trnType) => `${API_BASE_URL}/api/sales/${invoiceNo}/address${trnType ? `?trnType=${trnType}` : ''}`,
  RECEIVABLE_HISTORY: `${API_BASE_URL}/api/receivable/history`,
  RECEIVABLE_INVOICES: (isReturn) => `${API_BASE_URL}/api/receivable/invoices?returnInvoice=${isReturn}`,
  RECEIVABLE_CASH_ACCOUNTS: `${API_BASE_URL}/api/receivable/cash-accounts`,
  RECEIVABLE_COST_CENTERS: `${API_BASE_URL}/api/receivable/cost-centers`,
  RECEIVABLE_CURRENCIES: `${API_BASE_URL}/api/receivable/currencies`,
  RECEIVABLE_ACCOUNTS_INFO: `${API_BASE_URL}/api/receivable/accounts-info`,
  RECEIVABLE_SAVE: `${API_BASE_URL}/api/receivable/save`,
  // Payable
  PAYABLE_HISTORY: `${API_BASE_URL}/api/payable/history`,
  PAYABLE_INVOICES: (isReturn) => `${API_BASE_URL}/api/payable/invoices?returnInvoice=${isReturn}`,
  PAYABLE_SAVE: `${API_BASE_URL}/api/payable/save`,
  // General Voucher
  GENERAL_VOUCHER_TYPES: `${API_BASE_URL}/api/general-voucher/types`,
  GENERAL_VOUCHER_ACCOUNTS: `${API_BASE_URL}/api/general-voucher/accounts`,
  GENERAL_VOUCHER_HISTORY: `${API_BASE_URL}/api/general-voucher/history`,
  GENERAL_VOUCHER_SAVE: `${API_BASE_URL}/api/general-voucher/save`,
  // Expense Entry
  EXPENSE_ENTRY_TYPES: `${API_BASE_URL}/api/expense-entry/types`,
  EXPENSE_ENTRY_ACCOUNTS: `${API_BASE_URL}/api/expense-entry/accounts`,
  EXPENSE_ENTRY_HISTORY: `${API_BASE_URL}/api/expense-entry/history`,
  EXPENSE_ENTRY_SAVE: `${API_BASE_URL}/api/expense-entry/save`,
  // Salary Entry
  SALARY_ENTRY_TYPES: `${API_BASE_URL}/api/salary-entry/types`,
  SALARY_ENTRY_HISTORY: `${API_BASE_URL}/api/salary-entry/history`,
  SALARY_ENTRY_SAVE: `${API_BASE_URL}/api/salary-entry/save`,
};

export default API_BASE_URL;
